def print_first_film(fivemillionwatchedclub):
    premiere_days = list(fivemillionwatchedclub["Premiere to 5M"])
    theatrical_days = list(fivemillionwatchedclub["Theatrical to 5M"])
    one_million_days = list(fivemillionwatchedclub["1M to 5M"])
    two_million_days = list(fivemillionwatchedclub["2M to 5M"])
    three_million_days = list(fivemillionwatchedclub["3M to 5M"])
    four_million_days = list(fivemillionwatchedclub["4M to 5M"])

    print("First Film To Be Watched By 5 Million Members:")
    print("#1 Barbie in " + premiere_days[0] + " days (Premiere)")
    print("#1 Barbie in " + theatrical_days[0] + " days (Theatrical Release)")
    print("#1 Barbie in " + one_million_days[0] + " days (from 1M to 5M)")
    print("#1 Barbie in " + two_million_days[0] + " days (from 2M to 5M)")
    print("#1 Barbie in " + three_million_days[0] + " days (from 3M to 5M)")
    print("#1 Barbie in " + four_million_days[0] + " days (from 4M to 5M)\n")
